config/routes.rb
Quemfoi::Application.routes.draw do

  match 'certificates/search' => 'certificates#search', :as => :certificates_search
  match 'certificates/send_email' => 'certificates#send_email', :as => :certificate_send_email
  match 'certificates/edit_course/:id' => 'certificates#edit_course', :as => :certificate_edit_course
  match 'certificates/update_course' => 'certificates#update_course', :as => :certificate_update_course
  match ':id/participants' => 'courses#participants', :as => :participants
  match 'update_formation/:id' => 'activities#update_formation', :as => :update_formation
  match 'update_list/:id' => 'courses#update_list', :as => :update_list

  root :to => 'courses#index'
  resources :courses  do
    resources :activities, :except => [ :index, :show ]
    resources :certificates, :only => [ :index, :show ]
    member do
      get 'participants_status'
    end
  end

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  # GET /courses
  # GET /courses.xml
  def index
    @courses = Course.all(:order => 'reference_code ASC')

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @courses }
    end
  end

  # GET /courses/1
  # GET /courses/1.xml
  def show
    @course = Course.find(params[:id], :include => [ :activities ])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @course }
      format.csv do
        @activities = Activity.to_csv_file(@course.activities)
        @filename = 'atividades.csv'
        @output_encoding = 'UTF-8'
      end
    
    end
  end

  # GET /courses/new
  # GET /courses/new.xml
  def new
    @course = Course.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @course }
    end
  end

  # GET /courses/1/edit
  def edit
    @course = Course.find(params[:id])
  end

  # POST /courses
  # POST /courses.xml
  def create
    @course = Course.new(params[:course])

    respond_to do |format|
      if @course.save
        format.html { redirect_to(@course, :notice => t(:course_created) ) }
        format.xml  { render :xml => @course, :status => :created, :location => @course }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /courses/1
  # PUT /courses/1.xml
  def update
    @course = Course.find(params[:id])
    params[:course][:total_hours] = params[:course][:total_hours].gsub(',', '.')
    respond_to do |format|
      if @course.update_attributes(params[:course])
        format.html { redirect_to(courses_path, :notice => t(:course_updated) ) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @course.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.xml
  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    respond_to do |format|
      format.html { redirect_to(courses_url) }
      format.xml  { head :ok }
    end
  end

  def participants_status
    @course = Course.find(params[:id])
    @participants = @course.participants_info
    @course_total_time = @course.total_time
    respond_to do |format|
      format.html
    end
  end

  def participants
    @course = Course.find(params[:id])
    @activities = Activity.all(:conditions => "course_id = #{@course.id}")
    @activities_numbers = []
    @activities.each do |a|
      if !a.identificator_number.nil?
        @activities_numbers << a.identificator_number.gsub(' ', '')
      end
    end
    respond_to do |format|
      format.html
      format.xml  { render :xml => @activities }
      format.csv do
        @activities = Activity.to_csv_file(@activities)
        @filename = 'atividades.csv'
        @output_encoding = 'UTF-8'
      end
    
    end
  end

  def update_list
    participant = Participant.find(params[:id])
    participant.list = params[:list]
    participant.save
  end
end

app/views/courses/_form.html.erb
<% form_for(@course) do |f| %>
  <%= render "shared/error_messages", :target => @course %>
  <p>
    <%= f.label :identifier_to_certificate %>
    <%= f.text_field :identifier_to_certificate %>
  </p>
  
  <p>
    <%= f.label :identifier %>
    <%= f.text_field :identifier %>
  </p>
  <p>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :reference_code %>
    <%= f.text_field :reference_code %>
  </p>

  <p>
    <%= f.label :total_hours %>
    <%= f.text_field :total_hours %>
  </p>
  
  <p>
    <%= f.submit 'Salvar' %>
  </p>
<% end %>

app/views/courses/edit.html.erb
<h1>Editando Formação</h1>

<%= render :partial => "courses/form" %> 

<%= link_to 'Voltar para formações', courses_path, :class => "back_link"  %>
</br>
<%= link_to "Voltar para #{@course.identifier}", @course, :class => "back_link"  %>

app/views/courses/index.html.erb
<script>

  $(document).ready(function(){
    var oTable = $('.list').dataTable({
      "iDisplayLength": -1,
      "bAutoWidth": false,
      "bJQueryUI": true,
      "bSort": true,
      "sDom": '<"H"lTfr>t<"F"ip>',
      "oTableTools": {
         "sSwfPath": "DataTables-1.8.1/media/swf/copy_cvs_xls_pdf.swf"
      },
      "aaSorting": [[1,'asc'], [0,'desc']],
      "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 4, 5, 6] }],
        'oLanguage': {
          'oPaginate': {
            'sFirst': 'primeira',
            'sLast': 'ultima',
            'sNext': 'próxima',
            'sPrevious': 'anterior'
          },
          'sInfo': 'exibindo de _START_ até _END_ do total de _TOTAL_ registros',          
          'sInfoEmpty': "Mostrando de 0 até 0 de 0 registros",
          'sEmptyTable': 'não há registros para exibir',
          'sInfoFiltered': '- filtrando de _MAX_ registros',
          'sInfoPostFix': '',
          'sLengthMenu': 'exibe _MENU_ registros',
          'sProcessing': 'processando',
          'sSearch': 'filtrar',
          'sZeroRecords': 'não há registros para exibir'
        }
    });
  });
</script>

<h1>Formações</h1>
<div class="actions">
  <%= link_to 'Nova formação', new_course_path %>
</div>
<br>
<table class="list">
  <thead>
    <tr>
      <th>Identificação</th>
      <th>Código de referência</th>
      <th>Total de horas</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%=h course.identifier %></td>
        <td><%=h course.reference_code %></td>
        <td><%=h course.total_hours %></td>
        <% if [32, 3, 1, 2, 15, 17, 16, 11, 22].include?(course.id) %>
          <td style="padding-left: 10px;"><%= link_to 'Dados dos certificados', course_certificates_path(:course_id => course.id) %></td>
        <%else%>
          <td style="padding-left: 10px;"><%= link_to 'Dados dos certificados', course_certificates_path(:course_id => course.id) %></td>
        <%end%>
        <td style="padding-left: 10px;"><%= link_to 'Ver Atividades', course %></td>
        <td style="padding-left: 10px;"><%= link_to 'Participantes', participants_path(:id => course.id) %></td>
        <td style="padding-left: 10px;"><%= link_to 'Editar', edit_course_path(course) %></td>
        <td style="padding-left: 10px;"><%= button_to 'Apagar', {:action => 'destroy', :id => course.id}, :method => :delete %></td>
      </tr>
    <% end %>
  <tbody>
</table>

<br />

app/views/courses/new.html.erb
<h1>Nova Formação</h1>

<%= render :partial => "courses/form" %> 

<%= link_to 'Voltar', courses_path, :class => "back_link" %>

app/views/courses/participants.html.erb
<div id="participant_list">
  <% if @activities.count == 0%>
    O curso não possui atividades.
  <% else %>
    <% i = 0 %>
    <% @activities.each do |a| %>
      <% i += 1 %>
      <div class="participants_list">
        <ul class="activity_participants">
          <div style="padding: 10px 0; width: 200px;">
            <b><%= "#{a.name} - #{a.identificator_number}" %></b>
            <%= text_field_tag "formation_#{a.id}", nil, :value => a.formation, :class => "formation_field" %>
            <br>
            <%= "<b>Data:</b> #{a.date.try(:strftime, '%d/%m/%Y')}".html_safe %>
            <br>
            <%= "<b>Horário início:</b> #{a.start_time.try(:strftime, '%H:%M')}".html_safe %>
            <br>
            <%= "<b>Horário término:</b> #{a.end_time.try(:strftime, '%H:%M')}".html_safe %>
            <br>
            <%= "<b>Local:</b> #{a.place}".html_safe %>
            <br>
            <%= "<b>Educador:</b> #{a.leader}".html_safe %>
            <script>
              $(document).ready(function() {

                $('#<%="formation_#{a.id}"%>').change(function(){
                  $.ajax({url: "/update_formation/<%=a.id%>",
                    data: 'formation=' + $('#<%="formation_#{a.id}"%>').val()
                  })
                });
              });
            </script>
          </div>

          <% a.participants.all(:order => 'name ASC').each do |p| %>
            <li>
              <%= p.name %>
              <%= text_field_tag "list_#{p.id}", nil, :value => p.activities_numbers(@activities_numbers), :class => "participant_list_field" %>
            </li>
            <script>
              $(document).ready(function() {

                $('#<%="list_#{p.id}"%>').change(function(){
                  $.ajax({url: "/update_list/<%=p.id%>",
                    data: 'list=' + $('#<%="list_#{p.id}"%>').val()
                  })
                });
              });
            </script>
          <% end %>
        </ul>
      </div>
    <% end %>  
  <% end %>
</div>

app/views/courses/participants_status.html.erb
<h1>Frequência dos Participantes</h1>

<table>
  <tr>
    <th>Participante</th>
    <th>Frequência</th>
    <th>Aprovado?</th>
  </tr>
<% @participants.each do |info| %>
  <tr>
    <td><%=h info[0].name %></td>
    <td><%=h participant_frequency(info[1], @course_total_time) %></td>
    <td><%= approved(info[1], @course_total_time)  %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Voltar', courses_path %>

app/views/courses/show.html.erb
<h2><%= "#{@course.identifier} <i>#{@course.reference_code}</i> ".html_safe %>
  <span style="font-size: 10px;"><%= link_to 'Editar', edit_course_path(@course) %></span>
</h2>
<%= link_to 'Voltar', courses_path, :class => "back_link" %>
<div class="actions">
  <%= link_to 'Nova Lista de Presença', new_course_activity_path(@course) %>
  <%= link_to 'Exportar', "#{request.url}.csv" %>
</div>
</br>
<%= render :partial => "activities/list", :locals => { :activities => @course.activities } %>