config/routes.rb
Quemfoi::Application.routes.draw do

  match 'certificates/search' => 'certificates#search', :as => :certificates_search
  match 'certificates/send_email' => 'certificates#send_email', :as => :certificate_send_email
  match 'certificates/edit_course/:id' => 'certificates#edit_course', :as => :certificate_edit_course
  match 'certificates/update_course' => 'certificates#update_course', :as => :certificate_update_course
  match ':id/participants' => 'courses#participants', :as => :participants
  match 'update_formation/:id' => 'activities#update_formation', :as => :update_formation
  match 'update_list/:id' => 'courses#update_list', :as => :update_list

  root :to => 'courses#index'
  resources :courses  do
    resources :activities, :except => [ :index, :show ]
    resources :certificates, :only => [ :index, :show ]
    member do
      get 'participants_status'
    end
  end

end

app/models/certificate.rb
class Certificate < ActiveRecord::Base
  belongs_to :participant
  belongs_to :course

  def save_file
    create_pdf_file
    fill_with_data
    @pdf_file.render_file(file_path)
  end

  def period
    "#{self.course.start_date.try(:strftime, '%d/%m/%Y')} - #{self.course.end_date.try(:strftime, '%d/%m/%Y')}"
  end

private

  def fill_with_data
    course_description = format_course_description
    @pdf_file.draw_text participant.name, :at => [157,316], :size => 12
    @pdf_file.draw_text course.identifier_to_certificate, :at => [50,294], :size => 12
    @pdf_file.draw_text period, :at => [220,252], :size => 12
    @pdf_file.draw_text total_hours, :at => [547,252], :size => 12
    @pdf_file.draw_text frequency, :at => [678,252], :size => 12
    @pdf_file.draw_text I18n.localize(Time.now).split(',')[1], :at => [100,200], :size => 12
    y_position = 100
    course_description.each do |description|
      @pdf_file.draw_text description, :at => [545,y_position], :size => 6
      y_position -= 10 
    end
  end
  
  def format_course_description
    course_description = course.description 
    description_size = course_description.size
    if description_size > 40
      array = [] 
      string = ""
      break_control = 0
      course_description_splitted = course_description.split(" ")
      course_description_splitted.each do |description|
        if (break_control + description.size) > 70
          array << string
          break_control = 0
          string = ""
          string << "#{description} "
        else 
          string << "#{description} "
        end
        break_control += description.size
      end
      array << string
    else
      [course_description]
    end
  end

  def create_pdf_file
    @pdf_file = Prawn::Document.new(:template => "#{RAILS_ROOT}/lib/certificate/certificado_pec_ementa.pdf")
    @pdf_file.font_families.update(
        "pt sans" => {:normal => "#{RAILS_ROOT}/public/fonts/PT_Sans-Regular.ttf",
                      :bold => "#{RAILS_ROOT}/public/fonts/PT_Sans-Bold.ttf",
                      :italic => "#{RAILS_ROOT}/public/fonts/PT_Sans-Italic.ttf",
                      :bolditalic => "#{RAILS_ROOT}/public/fonts/PT_Sans-BoldItalic.ttf"
                      })
    @pdf_file.font "pt sans"
  end

end

app/controllers/certificates_controller.rb
class CertificatesController < ApplicationController

  def index
    @course = Course.find(params[:course_id])
    @reference_code = @course.reference_code.gsub(' ', '').gsub('(', '').gsub(')', '')
    @certificates = Certificate.all(:conditions => "course_id = #{params[:course_id]}", :include => [:participant])
    @approved_total = 0
    @disapproved_total = 0
    @almost_total = 0
    @certificates.each do |c|
      
      if c.frequency >= 75
        @approved_total += 1 
      else
        @disapproved_total += 1
      end

      if c.frequency >= 60 && c.frequency < 75
        @almost_total += 1
      end
    end
  end

  def search
    @participants = Participant.get_names
    @participant = Participant.find_by_name(params[:search])
    if @participant.nil?
      @certificates = []
    else
      @certificates = @participant.certificates
      @course = @participant.course
    end
    render :layout => false if request.xhr?
  end

  def send_email
    @participant = Participant.find(params[:participant_id])
    @participant.contact = params[:email]
    @participant.save
    @to_support = params[:to_support]
    if @to_support
      Resque.enqueue(CertificateSender,params[:certificate_id], 'certificados@paulofreire.org', @to_support)
    else
      Resque.enqueue(CertificateSender,params[:certificate_id], params[:email], @to_support)
    end
  end

  def edit_course
    @course_id = params[:id].to_i
    @participants = []
    Participant.all(:conditions => "course_id = #{@course_id}", :order => "name ASC").each do |p|
      next if p.name.blank?
      name = p.name.gsub("'","&#39;")
      @participants << name if !(@participants.include?(name))
    end
  end

  def update_course
    correct_participant = Participant.update_incorrect_participants(params)
    Resque.enqueue(CertificateGenerator, CertificateGenerator::FOR_PARTICIPANT, correct_participant.id)
    flash[:notice] = "Dados atualizados com sucesso"
    respond_to do |format|
      format.js if request.xhr?
      format.html
    end
  end

end

app/views/certificates/_search_bar.html.erb
<div id="search_bar">
  <% form_tag certificates_search_path, :id => 'search_form' do %>
    <%= text_field_tag :search, '', :size => 20 %>
    <%= submit_tag t('search'), :disable_with => t('please_wait_searching'), :id => 'search_submit' %>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    var data = <%=array_or_string_for_javascript(participants)%>;
    $( "#search" ).autocomplete(data, {max:10});
    $("#search_submit").attr("disabled","disabled");
    $("#search").keyup(function() {
      var $submit = $("#search_submit");
      if ( $("#search").val().length > 0 ) {
         $submit.removeAttr("disabled");
      } else {
         $submit.attr("disabled","disabled");
      }
    });
  });
</script>

app/views/certificates/edit_course.html.erb
<a id="update_names" href="#" onclick="$.post('/certificates/update_course', {course_id: <%=@course_id%>, selected_names: getSelectedNames(), correct_name: getCorrectName()});">Atualizar</a>
<table>
	<tr height="225">
		<td width="220" id="tdAllItems">
		<b>Todos os nomes</b>
		<div id="ListBoxAllItems" style="height:225px;"></div>
		</td>
		<td width="220" id="tdSelectedItems">
		<b>Nomes a serem mudados</b>
		<div id="ListBoxSelectedItems" style="height:225px;"></div>
		</td>
		<td width="220" id="tdCorrectItem">
		<b>Nome correto</b>
		<div id="ListBoxCorrectItem" style="height:225px;"></div>
		</td>
	</tr>
</table>

<script type="text/javascript">
	$(document).ready(function() {
    $('#new_review').submit(function (){
      $.post($(this).attr('action'), $(this).serialize(), null, "script");
    return false;
    });
		window.listBoxAllItems = new JSListBox({'containerSelector':'ListBoxAllItems'});
		window.listBoxSelectedItems = new JSListBox({'containerSelector':'ListBoxSelectedItems'});
		window.listBoxCorrectItem = new JSListBox({'containerSelector':'ListBoxCorrectItem'});

		var allItems = [];
    var participants = <%=array_or_string_for_javascript(@participants).html_safe%>;
    jQuery.each(participants, function() {
  		allItems.push(new MyListBoxItem(this));
    });
		window.listBoxAllItems.addItems(allItems);
	});

	MyListBoxItem = JSListBox.Item.extend({

		text: "",

		init: function(text) {
			this.text = text;
		},

		render: function() {
			return '<a href="#">' + this.text + '</a>';
		},

		onClick: function() {
			var item = new JSListBox.Item();
			item.value = this.text;
			items = window.listBoxSelectedItems.items
			if (items[0] != undefined){
        var selected_items = getItems(items);
			  if (jQuery.inArray(this.text, selected_items) == -1){
			    window.listBoxSelectedItems.addItem(item);
			  }
        insertItemInCorrectList(item);
			}
			else{
		    window.listBoxSelectedItems.addItem(item);
		    insertItemInCorrectList(item);
			}
		},

	});
	function getItems(items)
  {
    var my_items = [];
    jQuery.each(items, function() {
      my_items.push(this.value);
    });
   return my_items;
  }

  function insertItemInCorrectList(item){
    window.listBoxCorrectItem.items = [];
    window.listBoxCorrectItem.refresh();
    window.listBoxCorrectItem.addItem(item);
  }

  function getSelectedNames(){
  	items = window.listBoxSelectedItems.items;
  	selected_names = [];
    jQuery.each(getItems(items), function() {
      selected_names.push(this.toString());
    });
    return selected_names;
  }

  function getCorrectName(){
    return window.listBoxCorrectItem.items[0].value.toString();
  }
</script>

app/views/certificates/index.html.erb
<script>

  $(document).ready(function(){
    var oTable = $('.list').dataTable({
      "iDisplayLength": -1,
      "bAutoWidth": false,
      "bJQueryUI": true,
      "bSort": true,
      "sDom": '<"H"lTfr>t<"F"ip>',
      "oTableTools": {
         "sSwfPath": "DataTables-1.8.1/media/swf/copy_cvs_xls_pdf.swf"
      },
      "aaSorting": [[1,'desc'], [0,'asc']],
      "aoColumnDefs": [ { "bSortable": false, "aTargets": [] }],
        'oLanguage': {
          'oPaginate': {
            'sFirst': 'primeira',
            'sLast': 'ultima',
            'sNext': 'próxima',
            'sPrevious': 'anterior'
          },
          'sInfo': 'exibindo de _START_ até _END_ do total de _TOTAL_ registros',          
          'sInfoEmpty': "Mostrando de 0 até 0 de 0 registros",
          'sEmptyTable': 'não há registros para exibir',
          'sInfoFiltered': '- filtrando de _MAX_ registros',
          'sInfoPostFix': '',
          'sLengthMenu': 'exibe _MENU_ registros',
          'sProcessing': 'processando',
          'sSearch': 'filtrar',
          'sZeroRecords': 'não há registros para exibir'
        }
    });
  });
</script>

<h1><%= "Certificados do curso <i>#{@course.reference_code}</i>".html_safe %></h1>
<br>

<div style="float:lef">
  <%= "<b>Total de aprovados:</b> #{@approved_total}".html_safe %>&nbsp;
  <%= "<b>Total de reprovados:</b> #{@disapproved_total}".html_safe %>&nbsp;
  <%= "<b>Total entre 60% e 74%:</b> #{@almost_total}".html_safe %>
</div>

<div style="float:right">
  <%= link_to 'Exportar', "/dados_dos_certificados_#{@reference_code}.csv" %>
</div>

<table class="list">
  <thead>
    <tr>
      <th>Participante</th>
      <th>Porcentagem de Frequência (%)</th>
      <th>Total de horas</th>
      <th>Carga horária do curso</th>
    </tr>
  </thead>
    <tbody>
    <% @certificates.each do |certificate| %>
      <tr>
        <td><%=h certificate.participant.name %></td>
        <td><%=h certificate.frequency %></td>
        <td><%=h certificate.total_hours %></td>
        <td><%=h certificate.course_total_hours %></td>  
      </tr>
    <% end %>
  <tbody>
</table>

<br />

app/views/certificates/search.html.erb
<%= render :partial => "search_bar", :locals => {:participants => @participants} %>
<div id="certificates_data">
  <% if @certificates.count > 0%>
    <% @certificates.each do |c|%>
      <div class="certificate_data">
        <div>
          <b>Identificador:</b>&nbsp;<%= c.course.identifier %>
        </div>
        <div>
          <b>Descrição:</b>&nbsp;<%= c.course.description %>
        </div>
        <div>
          <b>Período:</b>&nbsp;<%= c.period %>
        </div>
        <div>
          <b>Total de horas:</b>&nbsp;<%= c.total_hours %>
        </div>
        <div>
          <b>Frequência:</b>&nbsp;<%= c.frequency %>%
        </div>
      </div>

      <div class="data_confirmation">
        <p>Os dados estão corretos?</p>
        <%= check_box_tag "certificicate_correct_#{c.id}" %> Sim
        <%= check_box_tag "certificicate_incorrect_#{c.id}" %> Não
      </div>

      <div id="email_with_certificate_<%= c.id %>" class="email_field" style="display:none">
        <p>Informe o seu e-mail para receber o certificado:</p>
        <% form_tag certificate_send_email_path do %>
         <%= text_field_tag :email, '', :size => 30 %>
         <%= hidden_field_tag :certificate_id, c.id %>
         <%= hidden_field_tag :participant_id, @participant.id %>
         <%= hidden_field_tag :to_support, false %>
         <%= submit_tag t('send'), :disable_with => t('please_wait')%>
        <% end %>
      </div>

      <div id="email_to_support_<%= c.id %>" class="email_field" style="display:none">
        <p>Informe o seu e-mail para que possamos entrar em contato a respeito da correção do certificado:</p>
        <% form_tag certificate_send_email_path do %>
         <%= text_field_tag :email, '', :size => 20 %>
         <%= hidden_field_tag :certificate_id, c.id %>
         <%= hidden_field_tag :participant_id, @participant.id %>
         <%= hidden_field_tag :to_support, true %>
         <%= submit_tag t('send'), :disable_with => t('please_wait')%>
        <% end %>
      </div>
      <script>
        $('#certificicate_correct_<%= c.id %>').change(function() {
          checked = $('#certificicate_correct_<%= c.id %>').is(':checked');
          if (checked == true) {
            $('#certificicate_incorrect_<%= c.id %>').attr('checked', false);
            $("#email_to_support_<%= c.id %>").hide();
            $("#email_with_certificate_<%= c.id %>").show();
          }
          else{
            $("#email_with_certificate_<%= c.id %>").hide();
          }
        });

        $('#certificicate_incorrect_<%= c.id %>').change(function() {
          checked = $('#certificicate_incorrect_<%= c.id %>').is(':checked');
          if (checked == true) {
            $('#certificicate_correct_<%= c.id %>').attr('checked', false);
            $("#email_to_support_<%= c.id %>").show();
            $("#email_with_certificate_<%= c.id %>").hide();
          }
          else{
            $("#email_to_support_<%= c.id %>").hide();
          }
        });
      </script>
    <% end %>
    <div class="course_list">
      Editar Curso
      <li> <%= link_to @course.identifier, certificate_edit_course_path(@course.id)%> </li>
    <div>
  <% else %>
    Não há certificados para o aluno informado.
  <% end %>
</div>

app/views/certificates/send_email.html.erb
<p>
<% if @to_support == "true"%>
  Em breve, iremos entrar em contato por e-mail.
<% else %>
  Um e-mail com o certificado foi enviado para o e-mail informado.
<% end %>
</p>
<br>
<%= link_to t('back'), certificates_path%>