config/routes.rb
Quemfoi::Application.routes.draw do

  match 'certificates/search' => 'certificates#search', :as => :certificates_search
  match 'certificates/send_email' => 'certificates#send_email', :as => :certificate_send_email
  match 'certificates/edit_course/:id' => 'certificates#edit_course', :as => :certificate_edit_course
  match 'certificates/update_course' => 'certificates#update_course', :as => :certificate_update_course
  match ':id/participants' => 'courses#participants', :as => :participants
  match 'update_formation/:id' => 'activities#update_formation', :as => :update_formation
  match 'update_list/:id' => 'courses#update_list', :as => :update_list

  root :to => 'courses#index'
  resources :courses  do
    resources :activities, :except => [ :index, :show ]
    resources :certificates, :only => [ :index, :show ]
    member do
      get 'participants_status'
    end
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :activities_participants, :dependent => :destroy
  has_many :participants, :through => :activities_participants
  belongs_to :course
# old schema
  # belongs_to :course
  # has_many :participants
  accepts_nested_attributes_for :participants,
                                :reject_if => lambda { |a| a[:name].blank? }

  validates_presence_of :name, :date, :start_time, :end_time, :place

  def duration
    (self.end_time - self.start_time)/3600
  end

  def self.to_csv_file(activities)
    array = []
    activities.each do |a|
      new_array = Array.new(5)
      new_array[0] = a.id
      new_array[1] = a.name
      new_array[2] = a.date.try(:strftime, "%d/%m/%Y")
      new_array[3] = a.place
      new_array[4] = a.identificator_number
      
      array << new_array
    end

    (0..4).each do |i|
        array[i] = "  " if array[i].blank?
      end
  
    array
    
  end
end

app/controllers/activities_controller.rb
# -*- coding: utf-8 -*-
class ActivitiesController < ApplicationController

  # GET /activities/new
  # GET /activities/new.xml

  before_filter :load_data, :except => [:index, :show]

  def new
    @course = Course.find(params[:course_id])
    @javascript_hash = @course.participants_as_javascript_hash
    @activity = @course.activities.build
    80.times { @activity.participants.build }
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @course = Course.find(params[:course_id])
    @activity = Activity.find(params[:id])
    20.times { @activity.participants.build }
    @javascript_hash = @course.participants_as_javascript_hash
  end

  # POST /activities
  # POST /activities.xml
  def create
    @course = Course.find(params[:course_id])
    @activity = @course.activities.build(params[:activity])
    @participants = @activity.participants.collect
    @activity.participants = []
    respond_to do |format|
      if @activity.save
        save_participants
        format.html { redirect_to( course_path(params[:course_id]), :notice => 'Lista de presença salva com sucesso') }
        format.xml  { render :xml => @activity, :status => :created, :location => @activity }
      else
        @javascript_hash = @course.participants_as_javascript_hash
        80.times { @activity.participants.build }
        format.html { render :action => "new" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.xml
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to( course_path(params[:course_id]), :notice => 'Lista de presença salva com sucesso') }
        format.html { redirect_to(@activity, :notice => 'activity was successfully updated.') }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @activity.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.xml
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to(course_path(params[:course_id])) }
      format.xml  { head :ok }
    end
  end

  def load_data
    @courses = Course.all.collect{|c| [c.identifier, c.id]}
  end

  def update_formation
    activity = Activity.find(params[:id])
    activity.formation = params[:formation]
    activity.save
  end

  def save_participants
    @participants.each do |p|
      participant = Participant.first(:conditions => {:name => p.name, :contact => p.contact, :course_id => p.course_id})
      if participant.nil?
puts "-" * 100
        puts Participant.count
        puts "-" * 100
        p = Participant.create(p.attributes)
        puts "-" * 100
        puts Participant.count
        puts "-" * 100
        ActivitiesParticipant.create(:activity_id => @activity.id, :participant_id => p.id)
      else
        ActivitiesParticipant.create(:activity_id => @activity.id, :participant_id => participant.id)
      end
      puts "-" * 100
        puts Participant.count
        puts "-" * 100
    end
  end
end

app/views/activities/_form.html.erb
<div id ="presence_list">
<% form_for [@course,@activity] do |f| %>
  <%= render "shared/error_messages", :target => @activity %>
  <div id="header">
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :identificator_number %>
      <%= f.text_field :identificator_number, :style => 'width: 60px' %>
      <%= f.label :formation %>
      <%= f.text_field :formation, :style => 'width: 40px' %>
      
    </p>
    </br>
    <p>
      <%= f.label :date %><%= f.date_select :date %>

      <%= f.label :start_time %><%= f.time_select :start_time %>

      <%= f.label :end_time %><%= f.time_select :end_time %>
    </p>
    </br>
    <p>
      <%= f.label :place %><%= f.text_field :place %>
      <%= f.label :leader %><%= f.text_field :leader %>
    </p>
    </br>
    <p>
      <%= f.label :course_id %>
      <%= f.select :course_id,  @courses %>
    </p>
    </br>
  </div>
  <hr/>
  <div id="attendance_list">
    <table id="participants">
      <tr>
        <th>Nome</th>
        <th>Segmento</th>
        <th>Unidade Educacional</th>
        <th>Contato</th>
      </tr>
     <% f.fields_for :participants do |pf| %>
       <%= render 'participant_fields', :pf => pf %>
     <% end %>
    </table>
      <p><%= link_to "Adicionar Participante", "#", :id => "add_participant" %></p>
   </div>
      <%= f.submit 'Salvar' %>
    </p>
<% end %>

</div>
<script>
 $(document).ready(function() {

 $("#add_participant").click(function() {
  var c = $("#participants tr").length - 1;
  row = "<tr> <td><input type='text' size='30' name='activity[participants_attributes][" + c + "][name]' id='activity_participants_attributes_"+ c + "_name' autocomplete='off' class='ac_input'></td><td><input type='text' size='30' name='activity[participants_attributes][" + c + "][group]' id='activity_participants_attributes_"+ c + "_group' autocomplete='off' class='ac_input'></td><td><input type='text' size='30' name='activity[participants_attributes][" + c + "][unit]' id='activity_participants_attributes_"+ c + "_unit' autocomplete='off' class='ac_input'></td><td><input type='text' size='30' name='activity[participants_attributes][" + c + "][contact]' id='activity_participants_attributes_"+ c + "_contact' autocomplete='off' class='ac_input'></td></tr>"
  $(row).appendTo($('#participants'));
  js = "<script>  $(document).ready(function(){  function findValueCallbackc(event, data, formatted) {    $('#activity_participants_attributes_" + c + "_group').val(formatted.split('-')[1]);    $('#activity_participants_attributes_" + c + "_unit').val(formatted.split('-')[2]);    $('#activity_participants_attributes_" + c + "_contact').val(formatted.split('-')[3]);  }  $('#activity_participants_attributes_" + c + "_name').result(findValueCallbackc);  var names = <%=@javascript_hash%>;  $( '#activity_participants_attributes_" + c + "_name' ).autocomplete(names, {    minChars: 0,    width: 310,    matchContains: 'word',    autoFill: false,    formatItem: function(row, i, max) {                  return row.name + ' - ' + row.group + ' - ' + row.unit + ' - ' + row.contact;                },    formatMatch: function(row, i, max) {                   return row.name + '-' + row.group + '-' + row.unit + '-' + row.contact;                 },    formatResult: function(row) {                    return row.name;                  }    });  });<\/script>"
  $('#participants').append(js);
 });

 });
</script>

app/views/activities/_list.html.erb
<script>

  $(document).ready(function(){
    var oTable = $('.list').dataTable({
      "iDisplayLength": -1,
      "bAutoWidth": false,
      "bJQueryUI": true,
      "bSort": true,
      "sDom": '<"H"lTfr>t<"F"ip>',
      "oTableTools": {
         "sSwfPath": "DataTables-1.8.1/media/swf/copy_cvs_xls_pdf.swf"
      },
      "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 4, 5] }],
        'oLanguage': {
          'oPaginate': {
            'sFirst': 'primeira',
            'sLast': 'ultima',
            'sNext': 'próxima',
            'sPrevious': 'anterior'
          },
          'sInfo': 'exibindo de _START_ até _END_ do total de _TOTAL_ registros',          
          'sInfoEmpty': "Mostrando de 0 até 0 de 0 registros",
          'sEmptyTable': 'não há registros para exibir',
          'sInfoFiltered': '- filtrando de _MAX_ registros',
          'sInfoPostFix': '',
          'sLengthMenu': 'exibe _MENU_ registros',
          'sProcessing': 'processando',
          'sSearch': 'filtrar',
          'sZeroRecords': 'não há registros para exibir'
        }
    });
  });
</script>

<table class="list">
  <thead>
    <tr>
      <th>Atividade</th>
      <th>Data</th>
      <th>Local</th>
      <th>Número identificador</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% activities.each do |activity| %>
      <tr>
        <td><%=h activity.name %></td>
        <td><%=l activity.date %></td>
        <td><%=h activity.place %></td>
        <td><%=h activity.identificator_number %></td>
        <td><%= link_to 'Ver lista', edit_course_activity_path(activity.course_id,activity.id) %></td>
        <td><%= button_to 'Apagar', {:controller => 'activities', :action => 'destroy', :course_id => activity.course_id, :id => activity.id}, :method => :delete %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/activities/_participant_fields.html.erb
<tr>
  <td><%= pf.text_field :name %></td>
  <td><%= pf.text_field :group %></td>
  <td><%= pf.text_field :unit %></td>
  <td><%= pf.text_field :contact %></td>
  <td><%= pf.hidden_field :course_id, :value => @course.id %></td>
</tr>

<% @i ||= 0 %>
<script>
  $(document).ready(function(){

  function findValueCallback<%=@i%>(event, data, formatted) {
    $("#activity_participants_attributes_" + <%=@i%> + "_group").val(formatted.split("-")[1]);
    $("#activity_participants_attributes_" + <%=@i%> + "_unit").val(formatted.split("-")[2]);
    $("#activity_participants_attributes_" + <%=@i%> + "_contact").val(formatted.split("-")[3]);
  }

  $("#activity_participants_attributes_" + <%=@i%> + "_name").result(findValueCallback<%=@i%>);

  var names = <%=@javascript_hash%>
  $( "#activity_participants_attributes_" + <%=@i%> + "_name" ).autocomplete(names, {
    minChars: 0,
    width: 310,
    matchContains: "word",
    autoFill: false,
    formatItem: function(row, i, max) {
                  return row.name + " - " + row.group + " - " + row.unit + " - " + row.contact;
                },
    formatMatch: function(row, i, max) {
                   return row.name + "-" + row.group + "-" + row.unit + "-" + row.contact;
                 },
    formatResult: function(row) {
                    return row.name;
                  }
    });
  });
</script>
<% @i += 1 %>

app/views/activities/edit.html.erb
<h1>Lista de Presença</h1>

<%= render :partial => "form" %>

<%= link_to 'Voltar', @course, :class => "back_link" %>

app/views/activities/index.html.erb
<h1>Listas de Presença</h1>



<br />

<%= link_to 'Nova Lista', new_activity_path %>

app/views/activities/new.html.erb
<h1>Lista de Presença</h1>

<%= render :partial => "form" %>

<%= link_to 'Voltar', @course, :class => "back_link" %>